(define (problem cube5)
(:domain cube)
(:requirements :strips :equality :typing :conditional-effects :disjunctive-preconditions)
 (:objects p0 p1 p2 p3 p4)
(:init
(and
(oneof (x-pos p0)
(x-pos p1)
(x-pos p2)
(x-pos p3)
(x-pos p4)
)
(oneof (y-pos p0)
(y-pos p1)
(y-pos p2)
(y-pos p3)
(y-pos p4)
)
(oneof (z-pos p0)
(z-pos p1)
(z-pos p2)
(z-pos p3)
(z-pos p4)
)
))
   (:goal (and (x-pos p2) (y-pos p2) (z-pos p2)))
)
